// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3mkj3SzV3AygMrSs3qAWZQt55ZBWp92U',
    appId: '1:708438026861:web:2729be4d31d74a738dad64',
    messagingSenderId: '708438026861',
    projectId: 'laundry-pos-5d67c',
    authDomain: 'laundry-pos-5d67c.firebaseapp.com',
    storageBucket: 'laundry-pos-5d67c.firebasestorage.app',
    measurementId: 'G-TF4C5H57QL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVLf_Gu5IQGrr9048_nYAfEADi0lNDLlc',
    appId: '1:708438026861:android:c7a0031e4d712b768dad64',
    messagingSenderId: '708438026861',
    projectId: 'laundry-pos-5d67c',
    storageBucket: 'laundry-pos-5d67c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn6h04z9EGrv8G_VA-HtjnFpXhZEzJ_gM',
    appId: '1:708438026861:ios:5328452d4bfe6b4d8dad64',
    messagingSenderId: '708438026861',
    projectId: 'laundry-pos-5d67c',
    storageBucket: 'laundry-pos-5d67c.firebasestorage.app',
    iosBundleId: 'com.example.laundryPos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn6h04z9EGrv8G_VA-HtjnFpXhZEzJ_gM',
    appId: '1:708438026861:ios:5328452d4bfe6b4d8dad64',
    messagingSenderId: '708438026861',
    projectId: 'laundry-pos-5d67c',
    storageBucket: 'laundry-pos-5d67c.firebasestorage.app',
    iosBundleId: 'com.example.laundryPos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3mkj3SzV3AygMrSs3qAWZQt55ZBWp92U',
    appId: '1:708438026861:web:2edb8fcfac7e284a8dad64',
    messagingSenderId: '708438026861',
    projectId: 'laundry-pos-5d67c',
    authDomain: 'laundry-pos-5d67c.firebaseapp.com',
    storageBucket: 'laundry-pos-5d67c.firebasestorage.app',
    measurementId: 'G-WHQHSFQKTQ',
  );
}
